% This script is to compute the approximation error of the gravitational
% attraction component using the combined Gauss-Legendre quadrature.
% The combined GLQ use GLQ with ordr of 5 to perform the modeling of
% tesseroids of 1degreex1degree in the near zone and use GLQ with order o 2
% to perfoem the modeling of tesseroids in the far zone.
% The parameter Psis is used to indicate the boundary between the near and
% far zone.
% The tesseroid model is generated by the function tess_genera_model(tessWid,tessThick,tessDen).
% Parameters: tessWid is the horizontal dimension, tessThick is the
% thickness(m) of thesseroids and tessDen is the density(kg/m^3) of the
% tesseroid.
% The latitude of the computation grid nodes varies from 0 to 90 degrees. 
% the global variable MEAN_EARTH_RADIUS the mean radius of the earth;
% the global variable G the gravitational constant in the program.
clear;clc;
global MEAN_EARTH_RADIUS;global G;global SI2mEOTVOS;global SI2MGAL;
SI2mEOTVOS=1000000000000.0;SI2MGAL=100000.0;MEAN_EARTH_RADIUS = 6378137.0;G = 0.0000000000667191;
%for parfor loop, using the local variables
MEAN_EARTH_RADIUS_local=MEAN_EARTH_RADIUS;G_local=G;SI2mEOTVOS_local=SI2mEOTVOS;SI2MGAL_local=SI2MGAL;
%Reading the roots and weights
Read_GL_rootandweights;

%tesseroid model information
tessWid=1;% the horizontal dimensions of the tesseroid unit is degrees
TopH=2000;BottomH=0;% the top and bottome surface
tessDen=2670;% the tesseroid density unit is kg/(m)^3
%Discretizing the shell into tesseroid model
tessmodel=tess_genera_model(tessWid,TopH,BottomH,tessDen);
[modnr,modnc]=size(tessmodel);
tessnumber=modnr
% the tess model variable name setting
tessmdNa=['tess_1degx1deg','_dr',num2str((TopH-BottomH)/1000),'km'];

%generating computation grid 
Hp=200000%Observation height(m)
WestGr=0;EastGr=tessWid/2;Spacinglon=tessWid/6;%computation grid range
SouthGr=0;NorthGr=90;Spacinglat=0.25;%computation grid range
%Generating the computation grid using the function grdi_gene();
griddata=grid_gene(WestGr,EastGr,SouthGr,NorthGr,Spacinglon,Spacinglat,Hp);
[gnr,gnc]=size(griddata);
gridnumber=gnr

%Closed formula for the gravitational attraction component
Density_shell=tessmodel(1,7);% Shell density is equal to tesseroid density
R1_shell=MEAN_EARTH_RADIUS+tessmodel(1,6); % inward radius R1 of the shell
R2_shell=MEAN_EARTH_RADIUS+tessmodel(1,5); % outer radius R2 of the shell
M1=Density_shell*4/3*pi*(R1_shell^3);
M2=Density_shell*4/3*pi*(R2_shell^3);
Analy_grav=G*(M2-M1)/((griddata(1,3)+MEAN_EARTH_RADIUS)^2)*SI2MGAL;

%Initializing the variables 
GLQ_grav=zeros(gridnumber,1);
Psis=5
tic
%Computing the gravitational contribution at computation grid nodes
%the parameter Psis indicate the spherical distance with respect to the
%computation point and it defines the boundary between the near and far
%zone
    for grind=1:1:gridnumber
        GLQ_grav(grind)=Pf_combined_GLQ(griddata,grind,tessmodel,Psis,5,2,MEAN_EARTH_RADIUS_local,G_local,...
                         GL_roots,GL_weights,SI2MGAL_local);
    end 
AbsoError=GLQ_grav - Analy_grav;
Differ_grav=[griddata(:,1:2) AbsoError];
toc
%Result variable name generation      
eval([[tessmdNa,'_ObservH',num2str(Hp/1000),'km_CombinedGLQ_Psis_',num2str(Psis)] '=Differ_grav;']);
save('A07_near_far_zone_combined_method',[tessmdNa,'_ObservH',num2str(Hp/1000),'km_CombinedGLQ_Psis_',num2str(Psis)],'-append');  %,'-append'
